import web3 from "./web3";

const address = "0xB13D854D8281F59C84E7173a6de638aAd23B8525";
const abi = [
	{
		inputs: [[Object]],
		stateMutability: "nonpayable",
		type: "constructor",
		constant: undefined,
		payable: undefined,
		signature: "constructor",
	},
	{
		inputs: [],
		name: "enterLottery",
		outputs: [],
		stateMutability: "payable",
		type: "function",
		constant: undefined,
		payable: true,
		signature: "0xc1af5785",
	},
	{
		inputs: [],
		name: "getLotteryId",
		outputs: [[Object]],
		stateMutability: "view",
		type: "function",
		constant: true,
		payable: undefined,
		signature: "0x900aafaf",
	},
	{
		inputs: [],
		name: "getManager",
		outputs: [[Object]],
		stateMutability: "view",
		type: "function",
		constant: true,
		payable: undefined,
		signature: "0xd5009584",
	},
	{
		inputs: [],
		name: "getPlayers",
		outputs: [[Object]],
		stateMutability: "view",
		type: "function",
		constant: true,
		payable: undefined,
		signature: "0x8b5b9ccc",
	},
	{
		inputs: [],
		name: "getPrizePool",
		outputs: [[Object]],
		stateMutability: "view",
		type: "function",
		constant: true,
		payable: undefined,
		signature: "0x884bf67c",
	},
	{
		inputs: [[Object]],
		name: "getWinnerByLotteryId",
		outputs: [[Object]],
		stateMutability: "view",
		type: "function",
		constant: true,
		payable: undefined,
		signature: "0xec44a343",
	},
	{
		inputs: [],
		name: "pickWinner",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
		constant: undefined,
		payable: undefined,
		signature: "0x5d495aea",
	},
];

export default new web3.eth.Contract(abi, address); //this is a local instance of the contract
